#!/usr/bin/env bash
# =============================================================================
# network/dns.sh — DNS Resolver Configuration
# =============================================================================
# Ubuntu / Debian  → systemd-resolved (/etc/systemd/resolved.conf)
# Rocky / RHEL     → NetworkManager (/etc/NetworkManager/conf.d/)
#
# CONFIGURATION (set in lib/env.sh):
#   PRIMARY_DNS   — Primary DNS server IP
#   SECONDARY_DNS — Secondary DNS server IP
#
# REQUIRES: sudo / root privileges
# =============================================================================
set -euo pipefail

DOTFILES_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$DOTFILES_ROOT/lib/env.sh"
source "$DOTFILES_ROOT/lib/log.sh"

log_info "Setting DNS servers: $PRIMARY_DNS, $SECONDARY_DNS"
log_info "Distro family: $DISTRO_FAMILY"

# =============================================================================
# Ubuntu / Debian — systemd-resolved
# =============================================================================
if [[ "$DISTRO_FAMILY" == "debian" ]]; then

  RESOLVED_CONF="/etc/systemd/resolved.conf"

  if [[ -f "$RESOLVED_CONF" ]]; then
    cp "$RESOLVED_CONF" "${RESOLVED_CONF}.bak.$(date +%Y%m%d_%H%M%S)"
    log_info "Backed up $RESOLVED_CONF"
  fi

  cat > "$RESOLVED_CONF" << EOF
# Generated by dotfiles/network/dns.sh — $(date)
[Resolve]
DNS=${PRIMARY_DNS} ${SECONDARY_DNS}
FallbackDNS=1.1.1.1 9.9.9.9
Domains=~.
DNSSEC=no
DNSStubListener=yes
EOF

  systemctl enable --now systemd-resolved
  systemctl restart systemd-resolved

# =============================================================================
# Rocky Linux / RHEL — NetworkManager
# =============================================================================
elif [[ "$DISTRO_FAMILY" == "rhel" ]]; then

  NM_DNS_CONF="/etc/NetworkManager/conf.d/dotfiles-dns.conf"
  mkdir -p "$(dirname "$NM_DNS_CONF")"

  cat > "$NM_DNS_CONF" << EOF
# Generated by dotfiles/network/dns.sh — $(date)
[global-dns-domain-*]
servers=${PRIMARY_DNS},${SECONDARY_DNS}
EOF

  log_info "DNS config written: $NM_DNS_CONF"

  # Also write /etc/resolv.conf directly as a fallback
  RESOLV_CONF="/etc/resolv.conf"
  if [[ -f "$RESOLV_CONF" ]]; then
    cp "$RESOLV_CONF" "${RESOLV_CONF}.bak.$(date +%Y%m%d_%H%M%S)"
  fi

  cat > "$RESOLV_CONF" << EOF
# Generated by dotfiles/network/dns.sh — $(date)
nameserver ${PRIMARY_DNS}
nameserver ${SECONDARY_DNS}
nameserver 1.1.1.1
EOF

  systemctl enable --now NetworkManager
  systemctl reload NetworkManager

else
  log_error "Unsupported distro family: '$DISTRO_FAMILY'. Cannot configure DNS."
fi

log_success "DNS configured: $PRIMARY_DNS / $SECONDARY_DNS"
