#!/usr/bin/env bash
# =============================================================================
# network/https.sh — HTTPS Deployment via Nginx + OpenSSL Self-Signed Cert
# =============================================================================
# Supports Ubuntu / Debian and Rocky Linux / RHEL.
#
# What this script does:
#   1. Install nginx (or reinstall if already present)
#   2. Generate a self-signed SSL certificate + private key via openssl
#   3. Write an nginx HTTPS virtual host config (HTTP → HTTPS redirect)
#   4. Enable and (re)start nginx
#
# CONFIGURATION (set in lib/env.sh):
#   NGINX_SERVER_NAME   — Domain / hostname for the virtual host
#   NGINX_HTTP_PORT     — HTTP listen port  (default: 80)
#   NGINX_HTTPS_PORT    — HTTPS listen port (default: 443)
#   SSL_CERT_DIR        — Directory to write the certificate (.crt)
#   SSL_KEY_DIR         — Directory to write the private key  (.key)
#   SSL_DAYS            — Certificate validity in days
#   SSL_COUNTRY         — Certificate subject: country code  (2-letter)
#   SSL_STATE           — Certificate subject: state / province
#   SSL_CITY            — Certificate subject: city / locality
#   SSL_ORG             — Certificate subject: organisation name
#
# REQUIRES: sudo / root privileges
# =============================================================================
set -euo pipefail

DOTFILES_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$DOTFILES_ROOT/lib/env.sh"
source "$DOTFILES_ROOT/lib/log.sh"

log_section "HTTPS Deployment (Nginx + OpenSSL)"

# ---------------------------------------------------------------------------
# Derived paths
# ---------------------------------------------------------------------------
SSL_CERT_FILE="${SSL_CERT_DIR}/nginx-selfsigned.crt"
SSL_KEY_FILE="${SSL_KEY_DIR}/nginx-selfsigned.key"

# ---------------------------------------------------------------------------
# Step 1: Install or reinstall nginx
# ---------------------------------------------------------------------------
log_info "Step 1/4 — Installing nginx..."

if [[ "$DISTRO_FAMILY" == "debian" ]]; then

  apt-get update -qq
  if dpkg -l nginx &>/dev/null 2>&1 && dpkg -l nginx | grep -q '^ii'; then
    log_info "nginx is already installed — reinstalling..."
    apt-get install --reinstall -y nginx
  else
    log_info "nginx not found — installing..."
    apt-get install -y nginx
  fi

elif [[ "$DISTRO_FAMILY" == "rhel" ]]; then

  if rpm -q nginx &>/dev/null 2>&1; then
    log_info "nginx is already installed — reinstalling..."
    dnf reinstall -y nginx
  else
    log_info "nginx not found — installing..."
    dnf install -y nginx
  fi

else
  log_error "Unsupported distro family: '$DISTRO_FAMILY'. Cannot install nginx."
fi

log_success "nginx installed."

# ---------------------------------------------------------------------------
# Step 2: Generate self-signed SSL certificate + key via openssl
# ---------------------------------------------------------------------------
log_info "Step 2/4 — Generating self-signed SSL certificate..."

mkdir -p "$SSL_CERT_DIR" "$SSL_KEY_DIR"

# Restrict key directory permissions (private key must not be world-readable)
chmod 700 "$SSL_KEY_DIR"

openssl req -x509 \
  -nodes \
  -days    "$SSL_DAYS" \
  -newkey  rsa:2048 \
  -keyout  "$SSL_KEY_FILE" \
  -out     "$SSL_CERT_FILE" \
  -subj    "/C=${SSL_COUNTRY}/ST=${SSL_STATE}/L=${SSL_CITY}/O=${SSL_ORG}/CN=${NGINX_SERVER_NAME}"

chmod 600 "$SSL_KEY_FILE"
chmod 644 "$SSL_CERT_FILE"

log_success "SSL certificate generated."
log_info   "  Certificate : $SSL_CERT_FILE"
log_info   "  Private key : $SSL_KEY_FILE"
log_info   "  Valid for   : $SSL_DAYS days"
log_info   "  CN          : $NGINX_SERVER_NAME"

# ---------------------------------------------------------------------------
# Step 3: Write nginx virtual host configuration
# ---------------------------------------------------------------------------
log_info "Step 3/4 — Writing nginx virtual host config..."

# Build the config content once (shared between both distro paths)
NGINX_CONF_CONTENT="# Generated by dotfiles https.sh — $(date '+%Y-%m-%d %H:%M:%S')
# Server: $NGINX_SERVER_NAME

# HTTP → HTTPS redirect
server {
    listen      ${NGINX_HTTP_PORT};
    server_name ${NGINX_SERVER_NAME};
    return 301  https://\$host\$request_uri;
}

# HTTPS virtual host
server {
    listen              ${NGINX_HTTPS_PORT} ssl;
    server_name         ${NGINX_SERVER_NAME};

    ssl_certificate     ${SSL_CERT_FILE};
    ssl_certificate_key ${SSL_KEY_FILE};

    # Modern TLS only
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    # HSTS (uncomment after verifying cert works)
    # add_header Strict-Transport-Security \"max-age=31536000; includeSubDomains\" always;

    root  /var/www/html;
    index index.html index.htm;

    location / {
        try_files \$uri \$uri/ =404;
    }
}
"

if [[ "$DISTRO_FAMILY" == "debian" ]]; then

  NGINX_CONF_PATH="/etc/nginx/sites-available/dotfiles-https.conf"
  NGINX_ENABLED_LINK="/etc/nginx/sites-enabled/dotfiles-https.conf"

  echo "$NGINX_CONF_CONTENT" > "$NGINX_CONF_PATH"

  # Remove the default site to avoid port conflicts
  rm -f /etc/nginx/sites-enabled/default

  # Enable the new site via symlink
  ln -sf "$NGINX_CONF_PATH" "$NGINX_ENABLED_LINK"

elif [[ "$DISTRO_FAMILY" == "rhel" ]]; then

  NGINX_CONF_PATH="/etc/nginx/conf.d/dotfiles-https.conf"

  echo "$NGINX_CONF_CONTENT" > "$NGINX_CONF_PATH"

  # Rocky: remove the default server block from nginx.conf if it listens on 80
  # to avoid conflicts (back it up first)
  if grep -q 'listen.*80' /etc/nginx/nginx.conf 2>/dev/null; then
    cp /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak
    # Comment out the default server block's listen 80 line
    sed -i 's/^\(\s*listen\s*80\)/# \1/' /etc/nginx/nginx.conf
    log_warn "Commented out default port-80 listen in /etc/nginx/nginx.conf (backup: nginx.conf.bak)"
  fi

fi

log_success "nginx config written to: $NGINX_CONF_PATH"

# Validate nginx configuration before restarting
log_info "Validating nginx configuration..."
if ! nginx -t 2>&1 | tee -a "$LOG_FILE"; then
  log_error "nginx configuration test failed. Review the output above."
fi
log_success "nginx configuration is valid."

# ---------------------------------------------------------------------------
# Step 4: Enable and (re)start nginx
# ---------------------------------------------------------------------------
log_info "Step 4/4 — Enabling and starting nginx..."

systemctl enable nginx
systemctl restart nginx

log_success "nginx is running with HTTPS."
log_info    "  HTTP  port : ${NGINX_HTTP_PORT}  (redirects to HTTPS)"
log_info    "  HTTPS port : ${NGINX_HTTPS_PORT}"
log_info    "  Config     : $NGINX_CONF_PATH"

log_success "HTTPS deployment complete."
