#!/usr/bin/env bash
# =============================================================================
# network/static-ip.sh — Static IP Configuration
# =============================================================================
# Ubuntu / Debian  → Netplan (/etc/netplan/)
# Rocky / RHEL     → NetworkManager CLI (nmcli)
#
# CONFIGURATION (set in lib/env.sh):
#   NETWORK_INTERFACE — Interface name, e.g. "eth0" (run `ip a` to find yours)
#   STATIC_IP         — IP address, e.g. "192.168.1.100"
#   SUBNET_MASK       — CIDR prefix, e.g. "24"
#   GATEWAY           — Default gateway, e.g. "192.168.1.1"
#   PRIMARY_DNS       — Primary DNS server
#   SECONDARY_DNS     — Secondary DNS server
#
# REQUIRES: sudo / root privileges
# WARNING:  Applying network changes will temporarily drop connectivity.
# =============================================================================
set -euo pipefail

DOTFILES_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$DOTFILES_ROOT/lib/env.sh"
source "$DOTFILES_ROOT/lib/log.sh"

# Skip if no static IP is configured
if [[ -z "${STATIC_IP:-}" ]]; then
  log_info "STATIC_IP is empty — skipping static IP configuration."
  exit 0
fi

log_info "Configuring static IP on $NETWORK_INTERFACE: $STATIC_IP/$SUBNET_MASK via $GATEWAY"
log_info "Distro family: $DISTRO_FAMILY"

# =============================================================================
# Ubuntu / Debian — Netplan
# =============================================================================
if [[ "$DISTRO_FAMILY" == "debian" ]]; then

  NETPLAN_FILE="/etc/netplan/99-dotfiles-static.yaml"

  cat > "$NETPLAN_FILE" << EOF
# Generated by dotfiles/network/static-ip.sh — $(date)
network:
  version: 2
  renderer: networkd
  ethernets:
    ${NETWORK_INTERFACE}:
      dhcp4: false
      addresses:
        - ${STATIC_IP}/${SUBNET_MASK}
      routes:
        - to: default
          via: ${GATEWAY}
      nameservers:
        addresses:
          - ${PRIMARY_DNS}
          - ${SECONDARY_DNS}
EOF

  chmod 600 "$NETPLAN_FILE"
  log_info "Netplan config written: $NETPLAN_FILE"

  log_warn "Applying Netplan — network will briefly reset..."
  netplan apply

# =============================================================================
# Rocky Linux / RHEL — nmcli (NetworkManager)
# =============================================================================
elif [[ "$DISTRO_FAMILY" == "rhel" ]]; then

  systemctl enable --now NetworkManager

  # Get the active connection name for this interface
  CON_NAME="$(nmcli -g GENERAL.CONNECTION device show "$NETWORK_INTERFACE" 2>/dev/null || true)"
  if [[ -z "$CON_NAME" ]]; then
    CON_NAME="dotfiles-static"
    nmcli connection add \
      type ethernet \
      con-name "$CON_NAME" \
      ifname "$NETWORK_INTERFACE"
    log_info "Created new NetworkManager connection: $CON_NAME"
  fi

  nmcli connection modify "$CON_NAME" \
    ipv4.method        manual \
    ipv4.addresses     "${STATIC_IP}/${SUBNET_MASK}" \
    ipv4.gateway       "$GATEWAY" \
    ipv4.dns           "${PRIMARY_DNS} ${SECONDARY_DNS}" \
    connection.autoconnect yes

  log_warn "Bringing up connection — network will briefly reset..."
  nmcli connection up "$CON_NAME"

else
  log_error "Unsupported distro family: '$DISTRO_FAMILY'. Cannot configure static IP."
fi

log_success "Static IP configured: $STATIC_IP/$SUBNET_MASK on $NETWORK_INTERFACE"
